name: "reneVolution"
profile:
  web: "http://www.renevolution.com"
  twitter: "renecalles"
  gravatar: "e590556cd6efce7b1dafb5fd4e6630c0"
hasbeen:
  cities:
    - "Cologne"
    - "Nümbrecht"
    - "Munich"
    - "Hamburg"
    - "Stuttgart"
    - "Berlin"
    - "Mannheim"
    - "Heielberg"
    - "Potsdam"
    - "Prague"
    - "Paris"
    - "London"
    - "Washington D.C."
    - "Philadelphia"
    - "New York"
    - "Buenos Aires"
    - "Gran Canaria"
    - "Tenerife"
    - "Dublin"
    - "Knokke-Heist"
    - "Amsterdam"
    - "Roermond"
    - "Kärnten, Feld am See"
    - "Domburg (NL)"
    - "Stockholm"
    - {"Åvik": "Åvik Brygge, Lindesnes, Norwegen"}
    - "Bergen"
    - "Lloret de Mar"
    - "Calella de la Costa"
    - "Lucerne"
    - "Vancouver"
    - "Geneva"
    - "Porto Viro"
